//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObmenApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdOperation { get; set; }
        public int IdClient { get; set; }
        public string Operation { get; set; }
        public string Value { get; set; }
        public decimal BuyRate { get; set; }
        public decimal SellRate { get; set; }
        public string Value2 { get; set; }
        public decimal CountMoney { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
