//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObmenApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int IdCourse { get; set; }
        public decimal EUR { get; set; }
        public decimal USD { get; set; }
        public decimal GBP { get; set; }
        public decimal UAH { get; set; }
        public System.DateTime Date { get; set; }
    }
}
